CREATE TABLE TB_CRIPTOMOEDA
(
ID INT IDENTITY(1,1) NOT NULL,
CODIGO VARCHAR(6) NOT NULL,
NOME VARCHAR(100) NOT NULL,
SITE VARCHAR(200) NULL,
CRIADO_EM DATETIME NOT NULL,
CONSTRAINT UQ_CODIGO UNIQUE(CODIGO)
)
